// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilterMapController from "./filter_map_controller"
application.register("filter-map", FilterMapController)

import HeaderController from "./header_controller"
application.register("header", HeaderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)


// import ProgressBarController from "./progress_bar_controller"
// application.register("progress-bar", ProgressBarController)

import QuestionsController from "./questions_controller"
application.register("questions", QuestionsController)

import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)
